'use client';
import {useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {useRouter} from 'next/navigation';
import {Activity,ArrowDownToLine,ArrowRight,BookOpen,Check,CheckCircle2,ChevronDown,ChevronRight,Clock,Code2,FileCode2,Filter,FolderGit2,Gauge,GitBranch,LayoutDashboard,LoaderCircle,LockKeyhole,LogOut,Play,Plus,Search,Settings2,Shield,ShieldCheck,Terminal,TriangleAlert,X,XCircle} from 'lucide-react';
import {stringify} from 'yaml';
import {api,download,supabase} from '@/lib/client';
import Standards from './standards';
import Remediation from './remediation';
import Workbench,{FindingWorkflow,ProjectContext} from './workbench';
import Integrations,{ScanTools} from './integrations';

type Row=Record<string,any>;
type Overview={session:Row;projects:Row[];scans:Row[];findings:Row[];alerts:Row[];runners:Row[];audit:Row[];finding_summary:Row[];sampled:boolean};
const nav=[{id:'overview',label:'Overview',icon:LayoutDashboard},{id:'projects',label:'Projects',icon:FolderGit2},{id:'findings',label:'Findings',icon:ShieldCheck},{id:'scans',label:'Scan history',icon:Activity},{id:'alerts',label:'Runtime signals',icon:TriangleAlert},{id:'policies',label:'Guardrails',icon:Settings2},{id:'runners',label:'Private runners',icon:Terminal},{id:'coverage',label:'Coverage',icon:BookOpen},{id:'integrations',label:'Integrations',icon:Code2}];
const severityOrder:Record<string,number>={critical:0,high:1,medium:2,low:3,info:4};
const date=(v:string)=>new Date(v).toLocaleString(undefined,{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'});
const revision=(v:string|undefined)=>v?(v.startsWith('snapshot:')?'snapshot '+v.slice(9,21):v.slice(0,12)):'Awaiting runner';
function Badge({value}:{value:string}) {return <span className={`badge ${value}`}>{value.replaceAll('_',' ')}</span>;}
function Empty({icon:Icon=FolderGit2,title,children,action}:{icon?:typeof Shield;title:string;children:React.ReactNode;action?:React.ReactNode}) {return <div className="empty"><div className="empty-icon"><Icon size={26}/></div><h3>{title}</h3><p>{children}</p>{action}</div>;}
function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}) {
  const element=useRef<HTMLElement>(null);
  useEffect(()=>{const previous=document.activeElement as HTMLElement|null;element.current?.focus();return()=>{if(previous?.isConnected)previous.focus();};},[]);
  return <div className="overlay" onMouseDown={e=>{if(e.target===e.currentTarget)onClose();}} onKeyDown={e=>{
    if(e.key==='Escape'){e.stopPropagation();onClose();}
    if(e.key==='Tab'){
      const controls=Array.from(element.current?.querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled),select:not(:disabled),textarea:not(:disabled),a[href],summary,[tabindex="0"]')??[]).filter(el=>el.getClientRects().length);
      const first=controls[0],last=controls.at(-1);
      if(e.shiftKey&&(document.activeElement===first||document.activeElement===element.current)){e.preventDefault();last?.focus();}
      else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}
    }
  }}><section ref={element} tabIndex={-1} role="dialog" aria-modal="true" aria-label={title} className="modal"><div className="modal-heading"><h2>{title}</h2><button className="icon-button" aria-label="Close" onClick={onClose}><X size={20}/></button></div>{children}</section></div>;
}

export default function Dashboard() {
  const router=useRouter();
  const [data,setData]=useState<Overview|null>(null),[health,setHealth]=useState<Row|null>(null),[tab,setTab]=useState('overview'),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState('');
  const [project,setProject]=useState('all'),[search,setSearch]=useState(''),[filter,setFilter]=useState('all'),[modal,setModal]=useState<string|null>(null),[selected,setSelected]=useState<Row|null>(null),[scanDetail,setScanDetail]=useState<Row|null>(null),[busy,setBusy]=useState(false),[ai,setAi]=useState('');
  const [policyProject,setPolicyProject]=useState(''),[policyText,setPolicyText]=useState(''),[credential,setCredential]=useState<Row|null>(null);
  const refresh=useCallback(async()=>{try{setData(await api('overview'));}catch(e){if((e as Row).status===401)setData(null);else setError((e as Error).message);}finally{setLoading(false);}},[]);
  useEffect(()=>{api('health').then(setHealth).catch(()=>{});refresh();},[refresh]);
  useEffect(()=>{if(!loading&&!data)router.replace('/signin');},[loading,data,router]);
  useEffect(()=>{if(!data)return;const timer=setInterval(refresh,8000);return()=>clearInterval(timer);},[!!data,refresh]);
  useEffect(()=>{if(notice){const timer=setTimeout(()=>setNotice(''),5000);return()=>clearTimeout(timer);}},[notice]);
  useEffect(()=>{if(data?.projects.length&&!policyProject){setPolicyProject(data.projects[0].id);setPolicyText(stringify(data.projects[0].policy));}},[data,policyProject]);
  const action=async(fn:()=>Promise<unknown>,message?:string)=>{setBusy(true);setError('');try{await fn();await refresh();if(message)setNotice(message);}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
  const findings=useMemo(()=>data?.findings.filter(f=>(project==='all'||f.project_id===project)&&(filter==='all'||f.severity===filter)&&`${f.title} ${f.data.path??''} ${f.rule}`.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>severityOrder[a.severity]-severityOrder[b.severity])??[],[data,project,filter,search]);
  const openFindings=findings.filter(f=>!['resolved'].includes(f.status)&&!(f.suppression_expires&&new Date(f.suppression_expires)>new Date()));
  const visibleScans=data?.scans.filter(s=>project==='all'||s.project_id===project)??[];
  const active=visibleScans.filter(s=>['queued','running'].includes(s.status));
  const startScan=(p:Row)=>action(async()=>{await api(`projects/${p.id}/scans`,'POST',{});setTab('scans');},'Scan queued. An assigned runner will pick it up.');
  const showScan=async(scan:Row)=>{try{setScanDetail(await api(`scans/${scan.id}`));setModal('scan');}catch(e){setError((e as Error).message);}};

  if(loading)return <div className="loading-screen"><Shield size={36}/><LoaderCircle className="spin"/>Opening your workspace…</div>;
  if(!data)return <div className="loading-screen"><LoaderCircle className="spin"/>Opening sign in…</div>;
  const current=nav.find(n=>n.id===tab)!;
  return <div className="shell">
    <aside className="sidebar" inert={!!modal}><a className="brand" href="/" aria-label="Sentinel home"><span className="brand-mark"><Shield size={22}/></span><span>sentinel<span className="brand-dot">.</span></span></a>
      <div className="workspace"><span className="workspace-avatar">S</span><div>My workspace<small>{health?.database==='embedded'?'Local development':'Private workspace'}</small></div><ChevronDown size={14}/></div>
      <div className="nav-label">WORKSPACE</div><nav>{nav.map(n=><button key={n.id} aria-label={n.label} aria-current={tab===n.id?'page':undefined} title={n.label} className={`nav-item ${tab===n.id?'active':''}`} onClick={()=>{setTab(n.id);setSearch('');setFilter('all');}}><n.icon size={18}/><span>{n.label}</span>{n.id==='findings'&&data.findings.filter(f=>f.status==='open').length>0&&<span className="nav-count">{data.findings.filter(f=>f.status==='open').length}</span>}{n.id==='alerts'&&data.alerts.filter(a=>a.status==='open').length>0&&<span className="signal-dot"/>}</button>)}</nav>
      <div className="sidebar-bottom"><div className="runner-note"><LockKeyhole size={17}/><div>Your code. Your infrastructure.<p>Scans run on private runners.</p></div></div><button className="nav-item" onClick={()=>setModal('settings')}><Settings2 size={17}/>Workspace settings</button><div className="profile"><span className="profile-avatar">{data.session.role[0].toUpperCase()}</span><div>Workspace {data.session.role}<small>Authenticated session</small></div><button className="icon-button" aria-label="Sign out" onClick={()=>action(async()=>{await api('auth/logout','POST',{});await supabase?.auth.signOut();setData(null);})}><LogOut size={16}/></button></div></div>
    </aside>
    <div className="main" inert={!!modal}><header className="topbar"><div className="breadcrumb">Workspace<ChevronRight size={14}/><strong>{current.label}</strong></div><div className="topbar-right"><span className="environment"><span/> {health?.database==='embedded'?'Local environment':'Connected workspace'}</span><span className="version">v0.1 alpha</span></div></header>
      <main className="content">
        {error&&<div className="banner error" role="alert"><TriangleAlert size={17}/>{error}<button aria-label="Dismiss error" onClick={()=>setError('')}><X size={16}/></button></div>}
        {notice&&<div className="banner success" role="status"><Check size={17}/>{notice}</div>}
        <div className="page-heading"><div><div className="eyebrow">SECURITY WORKSPACE</div><h1>{current.label==='Overview'?'A clearer view of your security.':current.label}</h1><p>{({overview:'Find the risks. Understand the evidence. Build with confidence.',projects:'Connect your code and define the boundaries of each assessment.',findings:'Evidence-backed findings, prioritized for the people fixing them.',scans:'Every assessment, its outcome, and what was actually checked.',alerts:'Security indicators from your running applications and proxies.',policies:'Define coding standards and the conditions for a safe release.',runners:'Keep source code and scan execution on infrastructure you control.',coverage:'Understand the reach and limits of your security assessments.',integrations:'Connect, diagnose, and fit security into your development workflow.'} as Row)[tab]}</p></div><button className="button primary" onClick={()=>setModal('project')}><Plus size={17}/>Connect project</button></div>
        <div className="context-bar"><label className="project-select"><FolderGit2 size={16}/><select aria-label="Filter project" value={project} onChange={e=>setProject(e.target.value)}><option value="all">All projects</option>{data.projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><span className="context-info"><Clock size={14}/> Results update automatically</span>{active.length>0&&<span className="live-count"><LoaderCircle size={13} className="spin"/>{active.length} scan{active.length>1?'s':''} in progress</span>}</div>

        {tab==='overview'&&<>
          {data.sampled&&<div className="banner">Overview shows the latest 100 scans, 200 alerts and 1,000 findings. Open the finding workbench to search every finding.</div>}
          <div className="stats"><Stat label="Open security findings" value={openFindings.filter(f=>f.category==='security'||f.category==='suspicious').length} icon={Shield} detail={`${openFindings.filter(f=>f.category==='security'&&['critical','high'].includes(f.severity)).length} high or critical`} tone="red"/><Stat label="Projects connected" value={data.projects.length} icon={FolderGit2} detail={`${data.projects.filter(p=>p.source_type==='github').length} GitHub · ${data.projects.filter(p=>p.source_type==='local').length} local`}/><Stat label="Completed assessments" value={visibleScans.filter(s=>s.status==='completed').length} icon={CheckCircle2} detail={`${visibleScans.filter(s=>s.gate==='incomplete').length} with coverage gaps`}/><Stat label="Open runtime alerts" value={data.alerts.filter(a=>a.status==='open'&&(project==='all'||a.project_id===project)).length} icon={Activity} detail="From connected log sources" tone="amber"/></div>
          {!data.projects.length&&<div className="welcome-panel"><div className="welcome-copy"><span className="pill"><ShieldCheck size={14}/> BUILT FOR YOUR CODEBASE</span><h2>Make security part<br/>of the way you build.</h2><p>Connect a project to inspect source code, dependencies, secrets, and architecture. Add a test environment to see how it behaves at runtime.</p><button className="button primary" onClick={()=>setModal('project')}>Connect your first project<ArrowRight size={16}/></button><small>No paid scanners required. AI is optional.</small></div><div className="pipeline-visual"><div className="pipeline-step"><FolderGit2/><div>Your project<small>Frontend · Backend · Infrastructure</small></div><CheckCircle2/></div><div className="pipeline-line"/><div className="pipeline-step center"><Shield/><div>Sentinel assessment<small>Code · Dependencies · Runtime</small></div><span className="mini-dot"/></div><div className="pipeline-line"/><div className="pipeline-step"><FileCode2/><div>Evidence & actionable fixes<small>Review · Prioritize · Verify</small></div><ArrowRight/></div></div></div>}
          <div className="overview-grid"><section className="panel"><PanelHead title="Findings by severity" subtitle="Unsuppressed findings requiring attention"/><div className="severity-chart">{['critical','high','medium','low','info'].map(v=>{const count=openFindings.filter(f=>f.severity===v).length;return <div className="severity-row" key={v}><span className={`severity-dot ${v}`}/><span>{v}</span><div className="bar-track"><div className={v} style={{width:count?`${Math.max(4,count/Math.max(1,openFindings.length)*100)}%`:'0%'}}/></div><strong>{count}</strong></div>;})}</div><div className="panel-footer"><span>Quality and architecture findings stay distinct.</span><button onClick={()=>setTab('findings')}>View findings<ArrowRight size={14}/></button></div></section><section className="panel"><PanelHead title="Latest assessments" subtitle="Outcomes include coverage and policy checks"/>{visibleScans.length?<div className="scan-list">{visibleScans.slice(0,4).map(s=><button key={s.id} className="scan-list-item" onClick={()=>showScan(s)}><div className={`scan-icon ${s.gate??s.status}`}><GitBranch size={17}/></div><div><strong>{s.project_name}</strong><small>{date(s.created_at)} · {revision(s.revision)}</small></div><Badge value={s.gate??s.status}/></button>)}</div>:<div className="compact-empty"><Activity size={22}/><p>Your assessment history will appear here.</p></div>}<div className="panel-footer"><span>Assessments are tied to source snapshots.</span><button onClick={()=>setTab('scans')}>All scans<ArrowRight size={14}/></button></div></section></div>
          <section className="panel"><PanelHead title="Priority findings" subtitle="Start with the highest-risk issues" action={<button className="text-button" onClick={()=>setTab('findings')}>View all<ArrowRight size={14}/></button>}/><FindingsTable findings={openFindings.slice(0,5)} onSelect={f=>{setSelected(f);setAi('');setModal('finding');}}/></section>
          <div className="coverage-note"><BookOpen size={17}/><p><strong>Visibility is part of security.</strong> A completed scan does not imply every flaw has been checked. Review engine coverage and manual verification requirements.</p><button className="text-button" onClick={()=>setTab('coverage')}>Explore coverage<ArrowRight size={14}/></button></div>
        </>}

        {tab==='projects'&&<div className="project-grid">{data.projects.filter(p=>project==='all'||p.id===project).map(p=>{const latest=data.scans.find(s=>s.project_id===p.id);return <section className="panel project-card" key={p.id}><div className="project-card-top"><span className="project-icon"><FolderGit2 size={23}/></span><Badge value={p.source_type}/></div><h2>{p.name}</h2><code>{p.source_ref}</code><div className="project-meta"><span><GitBranch size={14}/>{p.default_branch}</span><span><LockKeyhole size={14}/>{p.metadata_only?'Metadata only':'Redacted snippets'}</span></div><div className="project-health"><span>Latest quality gate</span>{latest?<Badge value={latest.gate??latest.status}/>:<span className="muted">Not assessed</span>}</div><div className="project-health"><span>Runtime telemetry</span><span className="muted">{p.last_telemetry?date(p.last_telemetry):'Not connected'}</span></div><div className="project-actions"><button className="button primary" disabled={busy} onClick={()=>startScan(p)}><Play size={14}/>Run assessment</button><button className="button" onClick={()=>{setSelected(p);setModal('project-settings');}}><Settings2 size={15}/>Settings</button></div></section>;})}{!data.projects.length&&<Empty title="Connect your first project">Use a registered local directory or a GitHub repository. Source stays on the runner.</Empty>}</div>}
        {tab==='findings'&&<Workbench project={project} canWrite={data.session.role!=='viewer'} onSelect={f=>{setSelected(f);setAi('');setModal('finding');}}/>}
        {tab==='integrations'&&<Integrations projects={data.projects} runners={data.runners} scans={data.scans} owner={data.session.role==='owner'}/>}
        {tab==='scans'&&<section className="panel"><PanelHead title="Assessment history" subtitle="Pass · Fail · Incomplete"/>{visibleScans.length?<div className="table-wrap"><table><thead><tr><th>Project / revision</th><th>Started</th><th>Status</th><th>Quality gate</th><th/></tr></thead><tbody>{visibleScans.map(s=><tr key={s.id}><td><button className="row-title" onClick={()=>showScan(s)}>{s.project_name}</button><small className="table-sub">{s.revision?.slice(0,12)??s.requested_revision?.slice(0,12)??'Snapshot pending'}</small></td><td>{date(s.created_at)}</td><td><Badge value={s.status}/></td><td>{s.gate?<Badge value={s.gate}/>:<span className="muted">Pending</span>}</td><td>{['queued','running'].includes(s.status)?<button className="text-button" onClick={()=>action(()=>api(`scans/${s.id}/cancel`,'POST',{}),'Cancellation requested.')}>Cancel</button>:<button className="text-button" onClick={()=>showScan(s)}>Report<ChevronRight size={14}/></button>}</td></tr>)}</tbody></table></div>:<Empty icon={Activity} title="No assessments yet">Run an assessment from a connected project. Enroll a private runner to process queued work.</Empty>}</section>}
        {tab==='alerts'&&<section className="panel"><PanelHead title="Runtime signals" subtitle="Indicators from application and proxy logs; not proof of exploitation"/>{data.alerts.filter(a=>project==='all'||a.project_id===project).length?<div className="scan-list">{data.alerts.filter(a=>project==='all'||a.project_id===project).map(a=><button className="scan-list-item" key={a.id} onClick={()=>{setSelected(a);setModal('alert');}}><span className="project-icon"><TriangleAlert size={18}/></span><div><strong>{a.title}</strong><small>{a.project_name} · {a.evidence.count} events · {date(a.last_seen)}</small></div><Badge value={a.severity}/><Badge value={a.status}/></button>)}</div>:<Empty icon={Activity} title="No runtime signals recorded">Connect the log collector to receive application security events. No alerts can also mean no telemetry is connected.</Empty>}<div className="panel-footer"><code>python -m runner.cli collect --config runner-settings.json --project PROJECT_ID --log app.jsonl</code></div></section>}
        {tab==='policies'&&<section className="panel"><PanelHead title="Project guardrails" subtitle="Versioned, declarative policy. No arbitrary execution."/>{data.projects.length?<div className="policy-editor"><label>Project<select value={policyProject} onChange={e=>{setPolicyProject(e.target.value);setPolicyText(stringify(data.projects.find(p=>p.id===e.target.value)!.policy));}}>{data.projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><textarea aria-label="Guardrails YAML" spellCheck={false} value={policyText} onChange={e=>setPolicyText(e.target.value)}/><div className="policy-actions"><p><strong>Advisory by default.</strong> Set mode to enforce to enable failing quality gates. Required checks that cannot run produce an incomplete result.</p><button className="button" onClick={()=>download('security-guardrails.yml',policyText)}><ArrowDownToLine size={15}/>Download YAML</button><button className="button primary" disabled={busy} onClick={()=>action(()=>api(`projects/${policyProject}/policy`,'PUT',{yaml:policyText}),'Guardrails saved. Applies to newly queued scans.')}><Check size={15}/>Save guardrails</button></div></div>:<Empty icon={Settings2} title="Guardrails need a project">Connect a project to customize security checks, architectural boundaries, exclusions, and CI thresholds.</Empty>}</section>}
        {tab==='runners'&&<><div className="info-panel"><Terminal size={23}/><div><h3>Your scans run here.</h3><p>Enroll a runner, download its settings, then explicitly register directories on that machine. The dashboard can request aliases, never arbitrary filesystem paths.</p><code>python -m runner.cli run --config runner-settings.json</code></div><button className="button primary" disabled={!data.projects.length} onClick={()=>setModal('runner')}><Plus size={15}/>Enroll runner</button></div><section className="panel"><PanelHead title="Registered runners" subtitle="Credentials are scoped to selected projects and shown only once"/>{data.runners.length?<div className="table-wrap"><table><thead><tr><th>Runner</th><th>Assigned projects</th><th>Last seen</th><th>Status</th><th/></tr></thead><tbody>{data.runners.map(r=><tr key={r.id}><td><strong>{r.name}</strong></td><td>{r.project_ids.length}</td><td>{r.last_seen?date(r.last_seen):'Not connected'}</td><td><Badge value={r.revoked_at?'revoked':r.last_seen&&Date.now()-new Date(r.last_seen).getTime()<120000?'online':'offline'}/></td><td>{!r.revoked_at&&<button className="text-button danger" onClick={()=>action(()=>api(`runners/${r.id}`,'DELETE'),'Runner credential revoked.')}>Revoke</button>}</td></tr>)}</tbody></table></div>:<Empty icon={Terminal} title="No runners enrolled">Connect a project, then create a runner credential and register its source directories locally.</Empty>}</section></>}
        {tab==='coverage'&&<><section className="panel"><PanelHead title="Assessment coverage" subtitle="Five supported languages. Detection depth varies by engine and framework."/><div className="coverage-grid">{[['SAST','Opengrep + original guardrails','Source patterns and supported data-flow analysis'],['Dependencies','Trivy','Known vulnerabilities in supported manifests and packages'],['Secrets','Gitleaks','Recognized secret patterns in files and available history'],['Runtime testing','ZAP','Discovered local/staging routes and supplied API definitions'],['Architecture','Declarative boundary rules','Configured imports, dependencies, and unsafe APIs'],['Runtime signals','Log collector','Only the events your applications actually supply']].map(([name,engine,detail])=><div className="coverage-card" key={name}><ShieldCheck size={20}/><h3>{name}</h3><strong>{engine}</strong><p>{detail}</p></div>)}</div></section><section className="panel standards"><PanelHead title="OWASP ASVS 5.0 requirement catalog" subtitle="Official requirements with evidence, manual review, unsupported, and not-run states"/><Standards project={project}/></section></>}
        <footer className="footer"><span><Shield size={14}/>Sentinel / Security guardrails</span><span>Evidence first. Coverage always visible.</span></footer>
      </main>
    </div>

    {modal==='project'&&<Modal title="Connect a project" onClose={()=>setModal(null)}><ProjectForm busy={busy} onSubmit={p=>action(async()=>{await api('projects','POST',p);setModal(null);setTab('projects');},'Project connected. Enroll a runner to begin scanning.')}/></Modal>}
    {modal==='project-settings'&&selected&&<Modal title={`${selected.name} settings`} onClose={()=>setModal(null)}><ProjectSettings p={selected} busy={busy} onSave={p=>action(async()=>{await api(`projects/${selected.id}`,'PATCH',p);setModal(null);},'Project settings saved.')} onDelete={()=>action(async()=>{await api(`projects/${selected.id}`,'DELETE');setProject('all');setModal(null);},'Project and its assessment data deleted.')}/>{data.session.role!=='viewer'&&<ProjectContext project={selected} onSaved={refresh}/>}</Modal>}
    {modal==='runner'&&<Modal title="Enroll a private runner" onClose={()=>{setModal(null);setCredential(null);}}>{credential?<><div className="banner success"><CheckCircle2 size={17}/>Runner credential created. Download it now; it will not be shown again.</div><p className="form-help">Register local aliases before starting the runner. Keep the settings file private.</p><pre>{'python -m runner.cli register --config runner-settings.json --alias my-app --path /path/to/app\npython -m runner.cli run --config runner-settings.json'}</pre><button className="button primary" onClick={()=>download('runner-settings.json',JSON.stringify({api_url:window.location.origin,token:credential.token,roots:{},allowed_targets:[],scanner_mode:'container'},null,2),'application/json')}><ArrowDownToLine size={16}/>Download runner settings</button></>:<form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);action(async()=>{setCredential(await api('runners','POST',{name:f.get('name'),project_ids:f.getAll('projects')}));});}}><label>Runner name<input name="name" required minLength={2} placeholder="My development machine"/></label><fieldset><legend>Assign projects</legend>{data.projects.map(p=><label className="checkbox" key={p.id}><input type="checkbox" name="projects" value={p.id} defaultChecked/>{p.name}</label>)}</fieldset><button className="button primary" disabled={busy}>Create scoped credential<ArrowRight size={15}/></button></form>}</Modal>}
    {modal==='finding'&&selected&&<Modal title="Finding details" onClose={()=>setModal(null)}><div className="finding-detail"><div className="finding-badges"><Badge value={selected.severity}/><Badge value={selected.category}/><Badge value={selected.status}/></div><h2>{selected.title}</h2><p className="muted">{selected.project_name} · {selected.engine} / {selected.rule}</p><div className="code-location"><FileCode2 size={16}/><code>{selected.data.path??selected.data.endpoint??'Project configuration'}{selected.data.line?`:${selected.data.line}`:''}</code></div>{selected.data.evidence&&<pre>{selected.data.evidence}</pre>}{selected.data.related_reports?.length>1&&<p className="muted">Related engine reports: {selected.data.related_reports.map((r:Row)=>r.engine+" / "+r.rule).join(", ")}. Original evidence is preserved separately.</p>}<h3>Why it matters</h3><p>{selected.data.impact}</p><Remediation finding={selected.data}/><div className="metadata"><span>Confidence: {selected.data.confidence}</span><span>{selected.data.cwe?.join(', ')}</span><span>Revision: {revision(selected.revision)}</span><span>First detected: {date(selected.first_seen)}</span></div><FindingWorkflow finding={selected} canWrite={data.session.role!=='viewer'} onChanged={refresh}/><div className="finding-actions"><button className="button" disabled={busy} onClick={()=>action(async()=>{await api(`findings/${selected.id}`,'PATCH',{status:'confirmed'});setModal(null);},'Finding confirmed.')}><Check size={14}/>Confirm</button><button className="button" onClick={()=>setModal('suppress')}>Suppress with expiry</button><button className="button" disabled={busy} onClick={()=>action(async()=>{const result=await api(`findings/${selected.id}/ai`,'POST',{});setAi(result.text);})}>Optional AI suggestion</button></div>{selected.data.patch&&<button className="button" onClick={()=>download('suggested-fix.patch',selected.data.patch)}>Download patch · unvalidated</button>}{ai&&<><h3>AI proposal · unvalidated</h3><pre className="ai-output">{ai}</pre><button className="button" onClick={()=>download('ai-suggestion.txt',ai)}>Download suggestion</button></>}</div></Modal>}
    {modal==='suppress'&&selected&&<Modal title="Suppress a finding" onClose={()=>setModal('finding')}><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);action(async()=>{await api(`findings/${selected.id}`,'PATCH',{status:f.get('status'),reason:f.get('reason'),expires_at:new Date(String(f.get('expiry'))).toISOString()});setModal(null);},'Suppression saved with an expiration.');}}><label>Decision<select name="status"><option value="accepted">Accept risk temporarily</option><option value="false_positive">False positive</option></select></label><label>Reason<textarea name="reason" minLength={8} required placeholder="Explain the evidence and review decision…"/></label><label>Expires<input name="expiry" type="datetime-local" required/></label><button className="button primary" disabled={busy}>Save suppression</button></form></Modal>}
    {modal==='scan'&&scanDetail&&<Modal title="Assessment report" onClose={()=>setModal(null)}><div className="report-heading"><Badge value={scanDetail.status}/>{scanDetail.gate&&<Badge value={scanDetail.gate}/>}<code>{revision(scanDetail.revision)}</code><button className="button" onClick={()=>action(async()=>download(`scan-${scanDetail.id}.json`,JSON.stringify(await api(`scans/${scanDetail.id}/export`),null,2),'application/json'))}><ArrowDownToLine size={14}/>Export</button></div>{scanDetail.error&&<div className="banner error">{scanDetail.error}</div>}<ScanTools scan={scanDetail} scans={data.scans}/><h3>Scanner execution and coverage</h3>{scanDetail.executions.length?scanDetail.executions.map((e:Row)=><div className="execution" key={e.id}><div><strong>{e.engine}</strong><small>{e.version} · {(e.duration_ms/1000).toFixed(1)}s</small><Badge value={e.status}/></div><p>{e.coverage.join(' · ')||'No completed coverage'}</p>{e.limitations.map((x:string)=><p className="execution-limitation" key={x}>{x}</p>)}{e.error&&<p className="danger">{e.error}</p>}</div>):<p className="muted">Awaiting scanner execution. Refresh the report after the runner completes.</p>}<h3>Inventory and quality metrics</h3><pre>{JSON.stringify({inventory:scanDetail.inventory,metrics:scanDetail.metrics},null,2)}</pre></Modal>}
    {modal==='alert'&&selected&&<Modal title="Runtime alert" onClose={()=>setModal(null)}><Badge value={selected.severity}/><h2>{selected.title}</h2><p>{selected.evidence.limitation}</p><pre>{JSON.stringify(selected.evidence,null,2)}</pre><div className="finding-actions">{['investigating','dismissed','resolved'].map(status=><button className="button" key={status} disabled={busy} onClick={()=>action(async()=>{await api(`alerts/${selected.id}`,'PATCH',{status});setModal(null);},'Alert updated.')}>{status}</button>)}</div></Modal>}
    {modal==='settings'&&<Modal title="Workspace settings" onClose={()=>setModal(null)}><p>Role: <strong>{data.session.role}</strong></p><p className="form-help">Organization ID: <code>{data.session.org}</code></p><h3>Access control</h3><p>Owners can assign existing authenticated user IDs. Maintainers manage projects and findings; viewers can review results.</p><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);action(()=>api('members','POST',{user_id:f.get('user'),role:f.get('role')}),'Member access saved.');}}><label>Supabase user UUID<input name="user" required placeholder="Existing authenticated user ID"/></label><label>Role<select name="role"><option value="viewer">Viewer</option><option value="maintainer">Maintainer</option></select></label><button className="button" disabled={busy}>Assign access</button></form><h3>Recent audit events</h3><div className="audit-list">{data.audit.map((a,i)=><div key={i}><code>{a.action}</code><small>{date(a.created_at)}</small></div>)}</div></Modal>}
  </div>;
}

function Stat({label,value,icon:Icon,detail,tone='green'}:{label:string;value:number;icon:typeof Shield;detail:string;tone?:string}) {return <section className="stat"><div className="stat-label">{label}<Icon size={17}/></div><div className="stat-value">{value}<span className={`stat-indicator ${tone}`}/></div><p>{detail}</p></section>;}
function PanelHead({title,subtitle,action}:{title:string;subtitle:string;action?:React.ReactNode}) {return <div className="panel-heading"><div><h2>{title}</h2><p>{subtitle}</p></div>{action}</div>;}
function FindingsTable({findings,onSelect}:{findings:Row[];onSelect:(f:Row)=>void}) {return findings.length?<div className="table-wrap"><table><thead><tr><th>Finding</th><th>Severity</th><th>Category</th><th>Status</th><th/></tr></thead><tbody>{findings.map(f=><tr key={f.id}><td><button className="row-title" onClick={()=>onSelect(f)}>{f.title}</button><small className="table-sub"><FileCode2 size={12}/>{f.data.path??f.data.endpoint??f.project_name}{f.data.line?`:${f.data.line}`:''}<span>· {f.engine}</span></small></td><td><Badge value={f.severity}/></td><td><span className="category">{f.category}</span></td><td><Badge value={f.status}/></td><td><button className="icon-button" aria-label={`View ${f.title}`} onClick={()=>onSelect(f)}><ChevronRight size={17}/></button></td></tr>)}</tbody></table></div>:<div className="compact-empty"><ShieldCheck size={24}/><p>No findings to display. Run an assessment and review its coverage.</p></div>;}

function ProjectForm({busy,onSubmit}:{busy:boolean;onSubmit:(p:Row)=>void}) {
  const [source,setSource]=useState('local'),[target,setTarget]=useState(false),[formError,setFormError]=useState('');
  return <form onSubmit={e=>{e.preventDefault();setFormError('');const f=new FormData(e.currentTarget);try{onSubmit({name:f.get('name'),source_type:source,source_ref:f.get('source'),...(source==='github'?{github_installation_id:Number(f.get('installation'))}:{}),default_branch:f.get('branch')||'main',components:JSON.parse(String(f.get('components')||'[]')),metadata_only:f.get('metadata')==='on',ai_enabled:false,target:target?{url:f.get('url'),environment:f.get('environment'),active:f.get('active')==='on',authorized:f.get('authorized')==='on',exclusions:String(f.get('exclusions')??'').split('\n').filter(Boolean),...(f.get('openapi')?{openapi:f.get('openapi')}:{}),...(f.get('credential_ref')?{credential_ref:f.get('credential_ref')}:{} )}:null});}catch{setFormError('Components must be a valid JSON array.');}}}>
    <label>Project name<input name="name" required minLength={2} maxLength={100} placeholder="Customer portal"/></label><div className="segmented"><button type="button" className={source==='local'?'selected':''} onClick={()=>setSource('local')}><Terminal size={15}/>Local directory</button><button type="button" className={source==='github'?'selected':''} onClick={()=>setSource('github')}><GitBranch size={15}/>GitHub repository</button></div><label>{source==='local'?'Registered runner alias':'Repository (owner/repo)'}<input name="source" required placeholder={source==='local'?'customer-portal':'your-org/customer-portal'}/></label><p className="form-help">{source==='local'?'Register this alias and its absolute directory on your runner. Local paths are never accepted by the dashboard.':'Requires a configured GitHub App installed on the selected repository.'}</p>{source==='github'&&<><label>GitHub installation ID<input name="installation" type="number" min="1" required/></label><label>Default branch<input name="branch" defaultValue="main"/></label></>}<details><summary>Monorepo components</summary><label>Component definitions (JSON)<textarea name="components" defaultValue="[]" placeholder={'[{"name":"web","root":"apps/web","framework":"Next.js"}]'}/></label></details><label className="checkbox"><input type="checkbox" name="metadata"/>Store metadata only (no code snippets)</label><label className="checkbox"><input type="checkbox" checked={target} onChange={e=>setTarget(e.target.checked)}/>Attach a local or staging target for DAST</label>{target&&<TargetFields/>}{formError&&<div className="banner error">{formError}</div>}<button className="button primary" disabled={busy}>{busy?<LoaderCircle className="spin" size={15}/>:<Plus size={15}/>}Connect project</button>
  </form>;
}
function TargetFields({target}:{target?:Row}) {return <fieldset><legend>Authorized runtime target</legend><label>Base URL<input name="url" type="url" defaultValue={target?.url} required placeholder="http://127.0.0.1:8080"/></label><label>Environment<select name="environment" defaultValue={target?.environment??'local'}><option value="local">Local</option><option value="staging">Staging</option></select></label><label>OpenAPI file (relative to registered project)<input name="openapi" defaultValue={target?.openapi} placeholder="openapi.yaml"/></label><label>Credential reference (local runner environment variable)<input name="credential_ref" defaultValue={target?.credential_ref} placeholder="STAGING_AUTH_TOKEN"/></label><label>Excluded paths (one per line)<textarea name="exclusions" defaultValue={target?.exclusions?.join('\n')} placeholder="/logout\n/admin/delete"/></label><label className="checkbox"><input type="checkbox" name="active" defaultChecked={target?.active}/>Enable active testing (2 requests/sec, 30-minute limit)</label><label className="checkbox"><input type="checkbox" name="authorized" required defaultChecked={target?.authorized}/>I am authorized to test this local/staging application.</label><p className="form-help">Also register this exact URL in the runner's allowed_targets list. Credentials are resolved on the runner.</p></fieldset>;}
function ProjectSettings({p,busy,onSave,onDelete}:{p:Row;busy:boolean;onSave:(b:Row)=>void;onDelete:()=>void}) {const [target,setTarget]=useState(!!p.target),[confirm,setConfirm]=useState(false);return <form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);onSave({name:f.get('name'),metadata_only:f.get('metadata')==='on',ai_enabled:f.get('ai')==='on',target:target?{url:f.get('url'),environment:f.get('environment'),active:f.get('active')==='on',authorized:true,exclusions:String(f.get('exclusions')??'').split('\n').filter(Boolean),...(f.get('openapi')?{openapi:f.get('openapi')}:{}),...(f.get('credential_ref')?{credential_ref:f.get('credential_ref')}:{} )}:null});}}><label>Name<input name="name" defaultValue={p.name} minLength={2} required/></label><label className="checkbox"><input type="checkbox" name="metadata" defaultChecked={p.metadata_only}/>Retain metadata only</label><label className="checkbox"><input type="checkbox" name="ai" defaultChecked={p.ai_enabled}/>Enable optional cloud AI for selected redacted snippets</label><p className="form-help">AI requires a server-side API key and may incur provider charges. Generated patches are unvalidated.</p><label className="checkbox"><input type="checkbox" checked={target} onChange={e=>setTarget(e.target.checked)}/>Attach a runtime target</label>{target&&<TargetFields target={p.target}/>}<button className="button primary" disabled={busy}>Save settings</button><div className="delete-zone"><p>Deleting this project also deletes its scans, findings, events, and alerts.</p><label className="checkbox"><input type="checkbox" checked={confirm} onChange={e=>setConfirm(e.target.checked)}/>I want to delete this project and its assessment data.</label><button type="button" className="button danger" disabled={!confirm||busy} onClick={onDelete}>Delete project</button></div></form>;}
