'use client';
import {useEffect,useState} from 'react';
import {api,download} from '@/lib/client';
import {ArrowDownToLine,CheckCircle2,Terminal,TriangleAlert} from 'lucide-react';
import {ConnectGithubButton} from './github-connect';
type Row=Record<string,any>;
export default function Integrations({projects,runners,scans,owner}:{projects:Row[];runners:Row[];scans:Row[];owner:boolean}) {
  const [state,setState]=useState<Row|null>(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[project,setProject]=useState(projects[0]?.id??'');
  const refresh=()=>api('integrations').then(setState).catch(e=>setMessage(e.message));useEffect(()=>{refresh();},[]);
  const p=projects.find(p=>p.id===project),r=runners.find(r=>!r.revoked_at&&r.project_ids.includes(project));
  const steps=[['Connect source',!!p,'Choose a registered local alias or a GitHub App repository.'],['Enroll a scoped runner',!!r,'Private runners → Enroll runner → Download settings.'],['Bring the runner online',!!r?.last_seen&&Date.now()-new Date(r.last_seen).getTime()<120000,'Register the source, check prerequisites, then start the runner.'],['Run and review',scans.some(s=>s.project_id===project&&s.status==='completed'),'Projects → Run assessment → Review execution coverage and findings.']];
  return <div className="integration-grid"><section className="panel"><div className="panel-heading"><div><h2>Connect in a few steps</h2><p>A guided path from source code to useful results.</p></div><Terminal size={22}/></div><div className="integration-body"><label>Project<select value={project} onChange={e=>setProject(e.target.value)}><option value="">Choose a project</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><ol className="setup-steps">{steps.map(([title,done,detail])=><li key={String(title)}>{done?<CheckCircle2 size={19}/>:<span className="step-dot"/>}<div><strong>{title}</strong><p>{detail}</p></div></li>)}</ol><h3>Run from the Sentinel installation</h3><pre>{`python -m runner.cli doctor --config runner-settings.json\npython -m runner.cli register --config runner-settings.json --alias ${p?.source_type==='local'?p.source_ref:'my-app'} --path /absolute/path/to/project\npython -m runner.cli run --config runner-settings.json`}</pre><p className="form-help">The doctor command checks Docker, prepared engines, advisory freshness, and registered directories without executing project code.</p></div></section>
    <section className="panel"><div className="panel-heading"><div><h2>Connection health</h2><p>Configured services and runner availability.</p></div></div><div className="integration-body"><dl className="health-list"><dt>Online runners</dt><dd>{state?.online_runners??'—'}</dd><dt>Queued scans</dt><dd>{state?.queued_scans??'—'}</dd><dt>Expired worker leases</dt><dd>{state?.expired_leases??'—'}</dd><dt>GitHub</dt><dd>{state?.github_connections?.length?`${state.github_connections.length} account connection(s)`:state?.github_configured?'Ready to connect':'Host setup required'}</dd><dt>Optional AI</dt><dd>{state?.ai_configured?'Provider configured; project opt-in required':'Disabled / unconfigured'}</dd></dl><h3>Connect your GitHub repositories</h3><p>Choose the account and repositories Sentinel can access on GitHub. Then select a repository when connecting a project.</p>{state?.github_connections?.map((connection:Row)=><p key={connection.installation_id}><CheckCircle2 size={16}/> {connection.account_login} connected</p>)}<ConnectGithubButton disabled={!owner||!state?.github_configured} onError={setMessage}/><p className="form-help">{!owner?'A workspace owner must connect GitHub.':!state?.github_configured?'Your host must finish GitHub setup before accounts can connect.':'Connect again to update repository access. No app credentials are needed here.'}</p>{state?.queued_scans>0&&!state?.online_runners&&<div className="banner"><TriangleAlert size={18}/>Queued assessments need an online runner with access to their project.</div>}<button className="button" onClick={refresh}>Refresh status</button></div></section>
    <section className="panel"><div className="panel-heading"><div><h2>CI and report integrations</h2><p>Portable commands and standard output formats.</p></div></div><div className="integration-body"><p>Run on an isolated worker with Sentinel installed and engines prepared. Replace the source path with your CI checkout. Keep Sentinel code and its configuration outside the untrusted checkout.</p><pre>{`python -m runner.cli scan --path /workspace/app --enforce \\\n  --output artifacts/assessment.json --sarif artifacts/assessment.sarif`}</pre><p>Exit codes: <strong>0 pass · 1 policy failure · 2 incomplete</strong>. Archive both reports even when the command fails. Add a reviewed baseline with <code>--baseline</code>.</p><p>Scan reports now export SARIF 2.1.0 for compatible code-scanning tools and CycloneDX SBOMs when Trivy produced them. GitHub availability depends on repository type and plan.</p><a className="button" href="https://docs.github.com/en/code-security/how-tos/scan-code-for-vulnerabilities/integrate-with-existing-tools/uploading-a-sarif-file-to-github" target="_blank" rel="noreferrer">GitHub SARIF setup ↗</a><p className="form-help">GitLab and Jenkins can archive these files; their native vulnerability dashboards use provider-specific formats and need an adapter.</p></div></section>
    <section className="panel"><div className="panel-heading"><div><h2>Exploit intelligence</h2><p>Optional CISA KEV and FIRST EPSS enrichment.</p></div></div><div className="integration-body"><p>Refresh sends only public CVE identifiers to FIRST and downloads CISA’s public catalog. Source code, project names, and credentials stay private. Enrichment covers up to 100 distinct CVEs per refresh.</p><p>CISA checked: {state?.kev_checked_at?new Date(state.kev_checked_at).toLocaleString():'Not fetched'}<br/>EPSS checked: {state?.epss_checked_at?new Date(state.epss_checked_at).toLocaleString():'Not fetched'}</p><button className="button primary" disabled={!owner||busy} onClick={async()=>{setBusy(true);try{const r=await api('intelligence/refresh','POST',{});setMessage(r.message??r.results.map((r:Row)=>`${r.source}: ${r.status} (${r.count})`).join(' · '));await refresh();}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}}>{busy?'Refreshing…':'Refresh public intelligence'}</button><p className="form-help">Owner access required. Missing data stays unknown; stale EPSS stops contributing to priority after seven days. Reachability is not inferred from a CVE.</p></div></section>{message&&<div className="banner" role="status">{message}</div>}
  </div>;
}

export function ScanTools({scan,scans}:{scan:Row;scans:Row[]}) {
  const [base,setBase]=useState(''),[diff,setDiff]=useState<Row|null>(null),[error,setError]=useState('');
  const exportFile=async(format:string)=>{try{const output=await api(`scans/${scan.id}/${format}`);download(`sentinel-${scan.id}.${format==='sarif'?'sarif':'cdx.json'}`,JSON.stringify(output,null,2),'application/json');}catch(e){setError((e as Error).message);}};
  return <div className="scan-tools"><div className="inline-actions"><button className="button" disabled={scan.status!=='completed'} onClick={()=>exportFile('sarif')}><ArrowDownToLine size={14}/>SARIF 2.1.0</button><button className="button" disabled={!scan.metrics?.sbom} onClick={()=>exportFile('sbom')}><ArrowDownToLine size={14}/>CycloneDX SBOM</button></div><details><summary>Compare assessments</summary><label>Baseline assessment<select value={base} onChange={e=>{setBase(e.target.value);setDiff(null);}}><option value="">Select a completed assessment</option>{scans.filter(s=>s.project_id===scan.project_id&&s.id!==scan.id&&s.status==='completed').map(s=><option key={s.id} value={s.id}>{new Date(s.created_at).toLocaleString()} · {s.revision?.slice(-12)} · {s.gate}</option>)}</select></label><button className="button" disabled={!base||scan.status!=='completed'} onClick={async()=>{try{setDiff(await api(`scans/${scan.id}/compare?base=${base}`));setError('');}catch(e){setError((e as Error).message);}}}>Compare with this report</button>{diff&&<><div className="comparison-grid">{['new','persistent','no_longer_detected','not_rechecked'].map(k=><div key={k}><strong>{diff[k].length}</strong><span>{k.replaceAll('_',' ')}</span></div>)}</div><p>{diff.limitation}</p><button className="button" onClick={()=>download('assessment-comparison.json',JSON.stringify(diff,null,2),'application/json')}>Download comparison</button></>}</details>{error&&<p className="danger" role="alert">{error}</p>}</div>;
}
