import Link from 'next/link';
import {Activity,ArrowRight,BookOpen,Check,Code2,GitBranch,Layers,LockKeyhole,ScanLine,Shield,ShieldCheck,Terminal} from 'lucide-react';
import SignIn,{type SignInOptions} from './sign-in';

const features=[
  {icon:ScanLine,title:'Assess code and dependencies',text:'Run static analysis, secret detection, dependency and infrastructure checks across your frontend and backend.'},
  {icon:ShieldCheck,title:'Understand what to fix first',text:'Review P0–P4 priorities, redacted evidence, rule-specific guidance, ownership and remediation deadlines.'},
  {icon:GitBranch,title:'Keep regressions out of releases',text:'Declare guardrails, apply CI quality gates, and compare assessments to track new and persistent findings.'},
  {icon:Activity,title:'See signals from running apps',text:'Collect structured application and proxy logs to flag authentication failures and suspicious request patterns.'},
  {icon:Terminal,title:'Keep execution under your control',text:'Connect local projects or GitHub repositories. Private runners execute scans on infrastructure you manage.'},
  {icon:BookOpen,title:'Know what was actually checked',text:'Inspect scanner coverage, errors and ASVS mappings. Export findings with SARIF and dependencies with an SBOM.'}
];
export function PublicBrand(){return <Link className="public-brand" href="/"><span><Shield size={23}/></span>sentinel<span className="public-brand-dot">.</span></Link>;}
export default function Landing({options}:{options:SignInOptions}) {
  return <div className="public-site"><a className="public-skip" href="#main-content">Skip to content</a><header className="public-header"><PublicBrand/><nav aria-label="Main navigation"><a href="#features">Features</a><a href="#workflow">How it works</a><Link className="public-workspace-link" href="/dashboard">Workspace<ArrowRight size={14}/></Link><a className="button primary" href="#sign-in">Sign in<ArrowRight size={15}/></a></nav></header>
    <main id="main-content"><section className="public-hero"><div className="public-hero-copy"><div className="hero-pill"><span/>SECURITY ASSESSMENT & GUARDRAILS</div><h1>Find the risks.<br/>See the evidence.<br/><em>Build with confidence.</em></h1><p>Bring code security, quality guardrails and application signals into one workspace—with a clear path from finding to fix.</p><div className="hero-actions"><a className="button primary" href="#sign-in">Open your workspace<ArrowRight size={17}/></a><a className="hero-secondary" href="#features">Explore the platform<ArrowRight size={16}/></a></div><div className="hero-assurances"><span><Check size={15}/>Local-first execution</span><span><Check size={15}/>Free core scanners</span><span><Check size={15}/>Reviewable fixes</span></div><div className="hero-mini-pipeline" aria-label="Assessment workflow"><span><Code2 size={16}/>Your project</span><ArrowRight size={14}/><span><ScanLine size={16}/>Assessment</span><ArrowRight size={14}/><span><ShieldCheck size={16}/>Actionable findings</span></div></div><SignIn options={options}/></section>
    <div className="language-strip"><span>ONE WORKSPACE. FIVE ECOSYSTEMS.</span><div>{['JavaScript / TypeScript','Python','Java','C#','Go'].map(name=><strong key={name}>{name}</strong>)}</div></div>
    <section className="public-section" id="features"><div className="public-section-heading"><div className="eyebrow">FROM DISCOVERY TO REMEDIATION</div><h2>Security that fits the way you build.</h2><p>Connect your source, review the evidence and keep the team focused on the next useful action.</p></div><div className="feature-grid">{features.map(({icon:Icon,title,text})=><article className="public-feature" key={title}><span><Icon size={22}/></span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
    <section className="public-workflow" id="workflow"><div><div className="eyebrow">A CLEAR PATH FORWARD</div><h2>Connect. Assess.<br/>Improve. Repeat.</h2><p>Start with advisory findings. Introduce release gates when your team is ready.</p><a href="#sign-in" className="button primary">Get started<ArrowRight size={16}/></a></div><ol>{[{icon:Layers,title:'Connect your project',text:'Choose a local source alias or GitHub repository, then enroll a scoped private runner.'},{icon:ScanLine,title:'Choose and run your checks',text:'Inspect available coverage and assess code, dependencies, configuration, and authorized runtime targets.'},{icon:ShieldCheck,title:'Turn evidence into improvements',text:'Assign findings, review recommended fixes, and rescan to measure what changed.'}].map(({icon:Icon,title,text},i)=><li key={title}><span className="workflow-number">0{i+1}</span><div><h3><Icon size={17}/>{title}</h3><p>{text}</p></div></li>)}</ol></section>
    <section className="public-boundary"><LockKeyhole size={23}/><div><h3>Your code. Your infrastructure. Your decisions.</h3><p>Scan execution stays on private runners. The dashboard retains selected redacted evidence or metadata. Optional cloud AI is separately enabled and may incur provider charges. Assessments show coverage limits and do not guarantee discovery of every vulnerability.</p></div></section></main>
    <footer className="public-footer"><PublicBrand/><span>Security assessment and application-event monitoring.</span><a href="#sign-in">Sign in<ArrowRight size={14}/></a></footer>
  </div>;
}
