'use client';
import {useEffect,useState} from 'react';
import {api,download} from '@/lib/client';
type Row=Record<string,any>;
export function History({kind,project,onSelect,onCancel}:{kind:'scans'|'alerts'|'audit';project:string;onSelect?:(row:Row)=>void;onCancel?:(row:Row)=>void}) {
  const [data,setData]=useState<Row|null>(null),[cursor,setCursor]=useState(''),[previous,setPrevious]=useState<string[]>([]),[error,setError]=useState('');
  useEffect(()=>{setCursor('');setPrevious([]);setData(null);},[project,kind]);
  useEffect(()=>{let active=true;const load=()=>api(`${kind}?limit=50${project!=='all'&&kind!=='audit'?`&project=${project}`:''}${cursor?`&cursor=${encodeURIComponent(cursor)}`:''}`).then(r=>{if(active){setData(r);setError('');}}).catch(e=>{if(active)setError(e.message);});load();const timer=setInterval(load,8000);return()=>{active=false;clearInterval(timer);};},[kind,project,cursor]);
  return <section className="panel"><div className="panel-heading"><div><h2>{kind==='scans'?'Assessment history':kind==='alerts'?'Runtime signals':'Audit history'}</h2><p>All records within retention · 50 per page</p></div><button className="button" disabled={!data} onClick={()=>download(`${kind}-page.json`,JSON.stringify(data,null,2),'application/json')}>Export page</button></div>{error&&<div className="banner error" role="alert">{error}</div>}{!data?<p className="muted">Loading…</p>:!data.items.length?<p className="integration-body">No records. Missing telemetry is a coverage gap; it does not establish that an application is safe.</p>:<div className="table-wrap"><table><thead><tr><th>{kind==='audit'?'Action':'Project'}</th><th>{kind==='scans'?'Baseline / revision':kind==='audit'?'Resource':'Signal'}</th><th>Status</th><th>Recorded</th><th/></tr></thead><tbody>{data.items.map((r:Row)=><tr key={r.id}><td>{r.project_name??r.action}</td><td>{kind==='scans'?<><code>{r.baseline_scope}</code><small className="table-sub">{r.revision?.slice(0,12)??'Pending snapshot'}</small></>:r.title??r.resource}</td><td>{r.status??'Recorded'}{r.gate&&` · ${r.gate}`}</td><td>{new Date(r.last_seen??r.created_at).toLocaleString()}</td><td>{onSelect&&<button className="text-button" onClick={()=>onSelect(r)}>Details</button>}{onCancel&&['queued','running'].includes(r.status)&&<button className="text-button" onClick={()=>onCancel(r)}>Cancel</button>}</td></tr>)}</tbody></table></div>}<div className="panel-footer"><button className="button" disabled={!previous.length} onClick={()=>{setCursor(previous.at(-1)??'');setPrevious(previous.slice(0,-1));}}>Previous</button><button className="button" disabled={!data?.next_cursor} onClick={()=>{setPrevious([...previous,cursor]);setCursor(data!.next_cursor);}}>Next</button></div></section>;
}
export default function Operations({project,onConfigure}:{project:string;onConfigure:(id:string)=>void}) {
  const [data,setData]=useState<Row|null>(null),[error,setError]=useState('');
  useEffect(()=>{let active=true;const load=()=>api('operations').then(x=>{if(active)setData(x);}).catch(e=>{if(active)setError(e.message);});load();const timer=setInterval(load,8000);return()=>{active=false;clearInterval(timer);};},[]);
  return <>{error&&<div className="banner error" role="alert">{error}</div>}<div className="project-grid">{data?.projects.filter((p:Row)=>project==='all'||p.id===project).map((p:Row)=><section className="panel" key={p.id}><div className="integration-body"><h2>{p.name}</h2><p>{p.online_runners?`${p.online_runners} runner(s) online`:p.assigned_runners?'Assigned runners offline. Start Docker and your runner service.':'Enroll a runner assigned to this project.'}</p><p>{p.queued_scans} queued · {p.expired_leases} expired lease(s)</p><p>DAST: {p.dast_configured?(p.dast_enabled?'Target configured; review scan execution coverage':'Target configured, but DAST is disabled in guardrails'):'URL and explicit authorization required in this project’s settings'}</p><p>Last runtime event: {p.last_event?new Date(p.last_event).toLocaleString():'None received'}</p>{p.collectors.map((c:Row)=><p key={`${c.source}:${c.environment}`}>Collector {c.source.slice(0,8)} · {c.environment}: <strong>{c.status}</strong> · {c.unparsed_total??c.unparsed} unusable line(s) since checkpoint creation</p>)}{!p.collectors.length&&<p>No collector connected. Monitoring coverage is unknown.</p>}<button className="button" onClick={()=>onConfigure(p.id)}>Configure this project</button><details><summary>Connect your application logs</summary><p>Run on your private runner. Replace the local log path; it is never sent to the dashboard. Use a separate checkpoint for each project/log/environment.</p><pre>{`python -m runner.cli collect --config runner-settings.json --project ${p.id} --log /absolute/path/app.jsonl --checkpoint .data/${p.id}-collector.json --environment staging`}</pre><p>Structured JSONL or Nginx access logs. Do not add request bodies, passwords, authorization headers or session tokens to logs. A healthy collector may have no traffic.</p></details></div></section>)}</div><History kind="audit" project="all"/></>;
}
