'use client';
import {useEffect,useState} from 'react';
import {api} from '@/lib/client';
export default function Team({owner}:{owner:boolean}) {
  const [members,setMembers]=useState<Record<string,any>[]>([]),[invitations,setInvitations]=useState<Record<string,any>[]>([]),[token,setToken]=useState(''),[message,setMessage]=useState('');
  const refresh=()=>{api('members').then(setMembers).catch(e=>setMessage(e.message));if(owner)api('invitations').then(setInvitations).catch(e=>setMessage(e.message));};
  useEffect(()=>{refresh();},[owner]);
  return <section className="panel"><div className="panel-heading"><div><h2>Workspace access</h2><p>Owners administer connections; maintainers assess and triage; viewers read results.</p></div></div><div className="integration-body">{message&&<p role="status">{message}</p>}{owner&&<form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{const result=await api('invitations','POST',{email:f.get('email'),role:f.get('role')});setToken(result.token);setMessage(result.message);refresh();}catch(error){setMessage((error as Error).message);}}}><label>Invite a verified email<input type="email" name="email" required maxLength={254}/></label><label>Role<select name="role"><option value="viewer">Viewer</option><option value="maintainer">Maintainer</option></select></label><button className="button primary">Create one-time invitation</button></form>}{token&&<><p>Shown once. Share this code privately; it expires in 7 days and only the invited verified email can redeem it.</p><code>{token}</code></>}<h3>Accept an invitation</h3><form onSubmit={async e=>{e.preventDefault();try{const result=await api('invitations/accept','POST',{token:new FormData(e.currentTarget).get('token')});localStorage.setItem('sentinel.organization',result.organization_id);window.location.reload();}catch(error){setMessage((error as Error).message);}}}><label>Invitation code<input name="token" required autoComplete="off" placeholder="sit_…"/></label><button className="button">Join workspace</button></form><p className="form-help">Requires a confirmed Supabase email. Codes are never put into URLs, and invitations do not grant owner access.</p><h3>Current members</h3>{members.map(m=><p key={m.user_id}><code>{m.user_id}</code> · {m.role}</p>)}{owner&&<><h3>Invitations</h3>{invitations.map(i=><p key={i.id}>{i.email} · {i.role} · {i.accepted_at?'Accepted':i.revoked_at?'Revoked':new Date(i.expires_at)<new Date()?'Expired':'Pending'} {!i.accepted_at&&!i.revoked_at&&<button className="text-button" onClick={async()=>{try{await api(`invitations/${i.id}`,'DELETE');refresh();}catch(error){setMessage((error as Error).message);}}}>Revoke</button>}</p>)}</>}</div></section>;
}
