'use client';
import {useEffect,useState} from 'react';
import {api} from '@/lib/client';
import {PRIORITIES,type Priority} from '@/lib/priority';
import {ArrowLeft,ArrowRight,Bookmark,Search,SlidersHorizontal} from 'lucide-react';
type Row=Record<string,any>;
function PriorityBadge({finding}:{finding:Row}) {
  const tier=finding.priority as Priority,details=PRIORITIES[tier];
  if(!details)return null;
  return <span className={`badge ${details.severity}`} title={[details.label,...(finding.priority_reasons??[])].join(' · ')} aria-label={`${tier}: ${details.label} priority`}>{tier}</span>;
}
const defaults={q:'',severity:'all',status:'actionable',category:'all',engine:'',assignee:'',overdue:'all',sort:'priority',page:1,limit:25};
export default function Workbench({project,onSelect,canWrite}:{project:string;onSelect:(f:Row)=>void;canWrite:boolean}) {
  const [filters,setFilters]=useState(defaults),[result,setResult]=useState<Row|null>(null),[views,setViews]=useState<Row[]>([]),[name,setName]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(true),[selected,setSelected]=useState<string[]>([]),[version,setVersion]=useState(0);
  useEffect(()=>{const timer=setInterval(()=>setVersion(v=>v+1),10000);return()=>clearInterval(timer);},[]);
  const update=(key:string,value:string)=>setFilters(f=>({...f,[key]:value,page:1}));
  useEffect(()=>{setFilters(f=>({...f,page:1}));},[project]);
  useEffect(()=>{api('views').then(setViews).catch(e=>setError(e.message));},[version]);
  useEffect(()=>{let current=true;setLoading(true);const timer=setTimeout(()=>{
    const q=new URLSearchParams(Object.entries({...filters,...(project!=='all'?{project}:{})}).map(([k,v])=>[k,String(v)]));
    api(`findings?${q}`).then(r=>{if(current){setResult(r);setSelected(ids=>ids.filter(id=>r.items.some((item:Row)=>item.id===id)));setError('');}}).catch(e=>{if(current)setError(e.message);}).finally(()=>{if(current)setLoading(false);});
  },250);return()=>{current=false;clearTimeout(timer);};},[filters,project,version]);
  const save=async()=>{try{await api('views','POST',{name,filters});setName('');setVersion(v=>v+1);}catch(e){setError((e as Error).message);}};
  return <section className="panel workbench"><div className="panel-heading"><div><h2>Remediation workbench</h2><p>Search every finding. Assign the work. Track the deadline.</p></div><SlidersHorizontal size={20}/></div>
    {error&&<div className="banner error" role="alert">{error}</div>}
    <div className="workbench-filters"><label className="wide">Search title, rule, package or file<div className="search"><Search size={16}/><input aria-label="Search all findings" value={filters.q} onChange={e=>update('q',e.target.value)} placeholder="CVE, SQL injection, app.py…"/></div></label>
      {([['severity','Severity',['all','critical','high','medium','low','info']],['status','Status',['actionable','all','open','confirmed','accepted','false_positive','resolved']],] as const).map(([key,label,options])=><label key={key}>{label}<select aria-label={label} value={filters[key]} onChange={e=>update(key,e.target.value)}>{options.map(o=><option key={o} value={o}>{o.replaceAll('_',' ')}</option>)}</select></label>)}
    </div><details className="advanced-filters"><summary>More filters and sorting</summary><div className="workbench-filters">
      {([['category','Category',['all','security','quality','architecture','suspicious']],['sort','Sort',['priority','newest','oldest','due']],['overdue','Deadline',['all','yes']]] as const).map(([key,label,options])=><label key={key}>{label}<select aria-label={label} value={filters[key]} onChange={e=>update(key,e.target.value)}>{options.map(o=><option key={o} value={o}>{key==='overdue'?(o==='yes'?'Overdue only':'All deadlines'):o.replaceAll('_',' ')}</option>)}</select></label>)}
      <label>Engine<input value={filters.engine} placeholder="e.g. trivy" onChange={e=>update('engine',e.target.value)}/></label><label>Owner<input value={filters.assignee} placeholder="Team or unassigned" onChange={e=>update('assignee',e.target.value)}/></label>
    </div></details><div className="saved-views"><Bookmark size={16}/><select aria-label="Saved finding views" defaultValue="" onChange={e=>{const view=views.find(v=>v.id===e.target.value);if(view)setFilters({...defaults,...view.filters,page:1});}}><option value="">Saved personal views</option>{views.map(v=><option key={v.id} value={v.id}>{v.name}</option>)}</select><input aria-label="New view name" maxLength={80} value={name} onChange={e=>setName(e.target.value)} placeholder="Name this view"/><button className="button" disabled={!name.trim()} onClick={save}>Save view</button><button className="button" onClick={()=>setFilters(defaults)}>Reset filters</button></div>
    {selected.length>0&&canWrite&&<form className="bulk-bar" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{await api('findings/assign','POST',{ids:selected,assignee:String(f.get('assignee')||''),due_at:f.get('due')?new Date(String(f.get('due'))+'T23:59:59Z').toISOString():null});setVersion(v=>v+1);}catch(e){setError((e as Error).message);}}}><strong>{selected.length} selected</strong><input name="assignee" aria-label="Bulk owner" placeholder="Owner / team" maxLength={100}/><input name="due" aria-label="Bulk due date" type="date"/><button className="button primary">Assign selected</button></form>}
    <div aria-live="polite" className="result-count">{loading?'Updating results…':`${result?.total??0} matching findings · page ${result?.page??1} of ${Math.max(1,result?.pages??1)}`}</div>
    <div className="table-wrap" aria-busy={loading}><table><thead><tr>{canWrite&&<th><input type="checkbox" aria-label="Select this page" checked={!!result?.items.length&&selected.length===result.items.length} onChange={e=>setSelected(e.target.checked?result?.items.map((r:Row)=>r.id)??[]:[])}/></th>}<th>Finding / source</th><th>Priority</th><th>Status</th><th>Owner / deadline</th></tr></thead><tbody>{result?.items.map((f:Row)=><tr key={f.id}>{canWrite&&<td><input type="checkbox" aria-label={`Select ${f.title}`} checked={selected.includes(f.id)} onChange={e=>setSelected(ids=>e.target.checked?[...ids,f.id]:ids.filter(id=>id!==f.id))}/></td>}<td><button className="row-title" onClick={()=>onSelect(f)}>{f.title}</button><small className="table-sub">{f.project_name} · {f.engine} · {f.data.path??f.data.endpoint??'Configuration'}</small><span className={`badge ${f.severity}`}>{f.severity}</span> <small>{f.category}</small>{f.kev&&<span className="badge critical">Known exploited</span>}</td><td><PriorityBadge finding={f}/></td><td><span className={`badge ${f.effective_status}`}>{f.effective_status.replaceAll('_',' ')}</span></td><td>{f.effective_assignee||<span className="muted">Unassigned</span>}<small className={`table-sub ${['open','confirmed'].includes(f.effective_status)&&new Date(f.effective_due_at)<new Date()?'danger':''}`}>Due {new Date(f.effective_due_at).toLocaleDateString()}</small></td></tr>)}</tbody></table></div>
    {!loading&&!result?.items.length&&<div className="compact-empty">No findings match these filters. Coverage remains available in each assessment.</div>}
    <div className="panel-footer"><p>P0 Immediate · P1 High · P2 Medium · P3 Low · P4 Informational. Risk factors can raise priority.</p><div className="inline-actions"><button className="button" disabled={loading||filters.page===1} onClick={()=>setFilters(f=>({...f,page:f.page-1}))}><ArrowLeft size={14}/>Previous</button><button className="button" disabled={loading||filters.page>=(result?.pages??1)} onClick={()=>setFilters(f=>({...f,page:f.page+1}))}>Next<ArrowRight size={14}/></button></div></div>
  </section>;
}

export function FindingWorkflow({finding,canWrite,onChanged}:{finding:Row;canWrite:boolean;onChanged:()=>void}) {
  const [notes,setNotes]=useState<Row[]>([]),[error,setError]=useState(''),[message,setMessage]=useState('');
  const load=()=>api(`findings/${finding.id}/notes`).then(setNotes).catch(e=>setError(e.message));
  useEffect(()=>{load();},[finding.id]);
  return <div className="workflow"><h3>Remediation ownership</h3>{finding.priority_reasons&&<p>Priority <PriorityBadge finding={finding}/>: {finding.priority_reasons.join(' · ')}. Reachability has not been established.</p>}
    {finding.epss!=null&&<p>EPSS {(finding.epss*100).toFixed(2)}% · published {String(finding.epss_date).slice(0,10)} {new Date(finding.epss_date).getTime()<Date.now()-7*86400000?'· stale':''}</p>}
    {finding.kev!=null&&<p>CISA KEV: {finding.kev?'listed':'not listed at last check'} · checked {new Date(finding.kev_checked_at).toLocaleDateString()}</p>}
    {error&&<p role="alert" className="danger">{error}</p>}{message&&<p role="status">{message}</p>}
    <form className="assignment-form" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{await api('findings/assign','POST',{ids:[finding.id],assignee:String(f.get('owner')||''),due_at:f.get('due')?new Date(String(f.get('due'))+'T23:59:59Z').toISOString():null});setMessage('Assignment saved.');onChanged();}catch(e){setError((e as Error).message);}}}><label>Owner or team<input name="owner" maxLength={100} defaultValue={finding.effective_assignee??finding.assignee??''} disabled={!canWrite}/></label><label>Override due date (UTC)<input name="due" type="date" defaultValue={finding.due_at?new Date(finding.due_at).toISOString().slice(0,10):''} disabled={!canWrite}/></label><button className="button" disabled={!canWrite}>Save assignment</button></form><p className="form-help">Blank date uses the project severity SLA measured from first detection. An empty owner explicitly leaves this finding unassigned.</p>
    <h3>Investigation notes</h3><form onSubmit={async e=>{e.preventDefault();const form=e.currentTarget;try{await api(`findings/${finding.id}/notes`,'POST',{body:new FormData(form).get('note')});form.reset();await load();}catch(e){setError((e as Error).message);}}}><label>Evidence or remediation update<textarea name="note" required maxLength={4000} disabled={!canWrite}/></label><button className="button" disabled={!canWrite}>Add note</button></form><div className="notes-list">{notes.map(n=><article key={n.id}><p>{n.body}</p><small>{new Date(n.created_at).toLocaleString()} · {n.author.slice(0,8)}</small></article>)}{!notes.length&&<p className="muted">No investigation notes yet.</p>}</div>
  </div>;
}

export function ProjectContext({project,onSaved}:{project:Row;onSaved:()=>void}) {
  const [message,setMessage]=useState(''),c=project.security_context??{criticality:'standard',exposure:'unknown',owner:'',sla_days:{critical:7,high:30,medium:90,low:180,info:365}};
  return <details className="context-editor"><summary>Business context and remediation SLAs</summary><p>These owner-supplied values influence prioritization and default deadlines.</p><form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{await api(`projects/${project.id}/context`,'PUT',{owner:f.get('owner'),exposure:f.get('exposure'),criticality:f.get('criticality'),sla_days:Object.fromEntries(Object.keys(c.sla_days).map(k=>[k,Number(f.get(k))]))});setMessage('Security context saved.');onSaved();}catch(e){setMessage((e as Error).message);}}}><label>Default owner or team<input name="owner" defaultValue={c.owner} maxLength={100}/></label><div className="assignment-form"><label>Criticality<select name="criticality" defaultValue={c.criticality}>{['standard','important','critical'].map(v=><option key={v}>{v}</option>)}</select></label><label>Exposure<select name="exposure" defaultValue={c.exposure}>{['unknown','internal','internet'].map(v=><option key={v}>{v}</option>)}</select></label></div><div className="workbench-filters">{Object.entries(c.sla_days).map(([k,v])=><label key={k}>{k} deadline (days)<input type="number" name={k} min={1} max={365} defaultValue={Number(v)} required/></label>)}</div><button className="button primary">Save security context</button><p role="status">{message}</p></form></details>;
}
